server { 
    listen 1233 ssl;
    listen [::]:1233 ssl;
    root /var/www/html;
    index index.html;

    server_name ijoubair.42.fr;

    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ =404;
    }
    
}